/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alibaba_Hello */

#ifndef _Included_com_alibaba_Hello
#define _Included_com_alibaba_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alibaba_Hello
 * Method:    sayHi
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_alibaba_Hello_sayHi
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
